version: '3'
services:
  db:
    container_name: 'db'
    image: postgres:9.6
    volumes:
      - ../../../tmp/db:/var/lib/postgresql/data
  web:
    container_name: 'web'
    build:
      context: ../../../
      dockerfile: ./server/docker/development/Dockerfile
      args:
        UID: $UID
        GID: $GID
    working_dir: '/myapp'
    volumes:
      - ../../../:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db