version: '3'
services:
  db:
    container_name: 'db'
    image: postgres
    user: 1000:1000
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    container_name: 'web'
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db