version: '3'
services:
  counter-golangci-lint:
    container_name: 'counter-golangci-lint'
    # user: $UID:$GID
    build:
      context: .
      args:
        UID: $UID
        GID: $GID
        UNAME: $UNAME
    tty: true
    working_dir: '/home/$UNAME/workspace'
    volumes:
      - ../../../:/home/$UNAME/workspace