version: '3'
services:
  ruby2-6-4:
    container_name: 'ruby2-6-4'
    user: $UID:$GID
    build:
      context: .
      args:
        UID: $UID
        GID: $GID
        UNAME: $UNAME
    tty: true
    working_dir: '/home/$UNAME/workspace'
    volumes:
      - ./workspace:/home/$UNAME/workspace