version: '3'
services:
  db:
    container_name: 'db'
    image: postgres:9.6
    restart: on-failure
    volumes:
      - ../../../tmp/db:/var/lib/postgresql/data
  web:
    container_name: 'web'
    user: $UID:$GID
    build:
      context: ../../../
      dockerfile: ./server/docker/development/Dockerfile
      args:
        UID: $UID
        GID: $GID
        UNAME: $UNAME
    stdin_open: true
    tty: true
    working_dir: '/home/$UNAME/myapp'
    volumes:
      - ../../../:/home/$UNAME/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db